### ISSUE TITLE
Bug: False positive result shown when theme slug is entered in non-lowercase for activation

### ISSUE THREAD

**Issue by arunsathiya** [wp-cli/extension-command#121]
**Steps to reproduce**: Follow the steps below to reproduce the issue. 

- Enter theme slug in non-lowercase when activating it (Examples: `wp theme activate Dara`, `wp theme 
- Notice a success message shown `Success: Switched to 'Dara' theme.`
- Enter `wp theme list` to notice that no themes are active

```
➜  local wp theme list
+-----------------+----------+--------+---------+
| name            | status   | update | version |
+-----------------+----------+--------+---------+
| dara            | inactive | none   | 1.2.1   |
| twentyseventeen | inactive | none   | 1.7     |
+-----------------+----------+--------+---------+
➜  local
```

**What is expected:** Theme activation does not go through, and the success notice is not shown.

**What happens instead:** A success message is shown, but no theme is not activated.

**Screencast indicating this behaviour:** https://asciinema.org/a/JICHDMDwcPjsVibxZMUlHOHRJ

In theory, slug is supposed to be entered in lowercase. 

-- 

- Tested on a local install of WordPress. WordPress 4.9.8
- PHP version: 7.2.8
- WP-CLI version: 2.0.0

**Comment by arunsathiya** [comment]
Although, upon visiting the site, Dara theme is indeed activated.

**Comment by wojsmol** [comment]
@arunsathiya Please post output of `wp --info`

**Comment by arunsathiya** [comment]
@wojsmol Here you go.

```
➜  local wp --info
OS:	Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
Shell:	/bin/zsh
PHP binary:	/usr/local/Cellar/php/7.2.8/bin/php
PHP version:	7.2.8
php.ini used:	/usr/local/etc/php/7.2/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/arunsathiya/sites/local
WP-CLI packages dir:	/Users/arunsathiya/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.0.0
➜  local
```

**Comment by schlessera** [comment]
Thanks for the report, @arunsathiya!

This is fixed in #126.

**Comment by davrosait** [comment]
@schlessera i agree with @preda-bogdan This should reflect same functionality as admin interface.
This breaks `wp theme activate Avada` whereas activation in admin interface succeeds.

**Comment by schlessera** [comment]
Yes, looks like I'm gonna revert this change for now.

Detecting which slugs will be valid for themes seems to be non-trivial, and Core does not take care of it as it does for plugins.

**Comment by schlessera** [comment]
#126 has been reverted, so reopening this issue for now.

**Comment by achyuthajoy** [comment]
Hey folks! I've checked this issue against multiple operating systems - Win/Linux/Mac. Here are my findings.

Mac & Windows doesn't take into account mixed case folder names and hence the existing WP-CLI will switch the theme. (e.g. `wp theme activate TwentySeventeen`). But it won't set the theme as active in `wp theme list` because the stylesheet name is different - `TwentySeventeen`.

Here are some screenshots from Mac (Windows is similar)

![screen shot on 2019-03-02 at 10-29-25](https://user-images.githubusercontent.com/1161872/53694302-f4bd8b80-3dd2-11e9-90e7-ce4d3190cdfa.png)

<img width="1504" alt="screen shot 2019-03-02 at 10 30 38" src="https://user-images.githubusercontent.com/1161872/53694315-1159c380-3dd3-11e9-8de9-79069edb2bb0.png">

![screen shot 2019-03-02 at 10 31 14](https://user-images.githubusercontent.com/1161872/53694313-07d05b80-3dd3-11e9-91fc-9b8b40c5755f.png)

---

But on Linux, it is possible to create similar folder names `twentyseventeen` & `TwentySeventeen`. Hence executing `wp theme activate TwentySeventeen` will result in an error since the specified folder doesn't exist.

Here is a screenshot from Linux.

![screen shot on 2019-03-03 at 16-50-03](https://user-images.githubusercontent.com/1161872/53694412-837ed800-3dd4-11e9-9849-f24910f33f8f.png)

---

**Solutions**

1. Allow mixed case slugs in WPCLI. I'm deciding against this because, if there are similar theme names, doing a like search will return multiple themes resulting in error. 
2. Equalize the current behavior on Linux across all operating systems. Slugs will become case-sensitive and returns an error when exact match is not found.

I've opted the second solution since more than 60% of web servers uses Linux.

I'll be adding a new pull request referencing this issue shortly.
