### ISSUE TITLE
status and list should show both current version and version of updates

### ISSUE THREAD

**Issue by halfgaar** [wp-cli/extension-command#134]
The status command doesn't show the version of the available update:

![cli](https://user-images.githubusercontent.com/142686/45595223-beb55800-b9a8-11e8-9cda-c3617ddb0ae3.png)

Neither does the list command:

![cli2](https://user-images.githubusercontent.com/142686/45595279-50bd6080-b9a9-11e8-852e-394661e087d6.png)

Both of them should show both versions, because now I can't make informed decisions about the impact of the update.

**Comment by schlessera** [comment]
@halfgaar The lists only show the default fields because screen estate is limited, but there are more fields available in case you need them. If you want to have a list that includes the version to update to, you need to include the `update_version` field as well.

Example:
<img width="739" alt="image 2018-09-18 at 2 29 05 pm" src="https://user-images.githubusercontent.com/83631/45687474-36bd8280-bb4f-11e8-9786-917ac4a900c6.png">
