### ISSUE TITLE
Using this command  wp plugin is-active hello Error: 'is-active' is not a registered subcommand of 'plugin'. See 'wp help plugin' for available subcommands.

### ISSUE THREAD

**Issue by ranjithancr** [wp-cli/extension-command#155]

**Comment by schlessera** [comment]
I cannot confirm this, I assume it is a problem of how you installed WP-CLI (old version, requiring framework wp-cli instead of bundle wp-cli-bundle, ...).

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support
