### ISSUE TITLE
wp plugin command rely on cache rather than refreshing

### ISSUE THREAD

**Issue by ochamber** [wp-cli/extension-command#183]
Hi,

I try to update all-in-one-wp-migration-unlimited-extension thru 
#wp --allow-root --path=/opt/bitnami/wordpress plugin update all-in-one-wp-migration-unlimited-extension
+---------------------------------------------+----------+--------+---------+
| name                                                                 | status       | update  | version  |
+---------------------------------------------+----------+--------+---------+
..
| all-in-one-wp-migration-unlimited-extension | active        | none     | 2.25      |
..
#This was install thru a zip file as it is a billable plugin
Trying to update thru
#wp --allow-root --path=/opt/bitnami/wordpress plugin status all-in-one-wp-migration-unlimited-extension
#wp --allow-root --path=/opt/bitnami/wordpress plugin update all-in-one-wp-migration-unlimited-extension

It says :
Plugin all-in-one-wp-migration-unlimited-extension details:
    Name: All-in-One WP Migration Unlimited Extension
    Status: Active
    Version: 2.25
    Author: ServMask
    Description: Extension for All in One WP Migration that enables unlimited size exports and imports
Success: Plugin already updated.

But this is tot the last version. Thru UI, I get :
"There is a new version of All-in-One WP Migration Unlimited Extension available. View version 2.30 details or update now."

Once I've access thru the UI, the update is done correctly with #wp --allow-root ... command.
This let me think that the wp command rely on cache rather than refreshing.

As seen  is multiple post, there's a core check update but no equivalent for plugins

I've found multiple descriptions of the same problem but none of the solution described solves my issue : 

1/wp plugin update-all should check for updates rather than rely on the cache
https://github.com/wp-cli/wp-cli/issues/549
2/ Missing command: wp plugin check-update #3285
See : https://github.com/wp-cli/wp-cli/issues/3285
...

Solution I woul'd like : 
2 options: 
plugins check updates or plugin check update <plugin>
or
refresh cache with plugin list

Thanks for your help. Best regards. Olivier.

**Comment by planetahuevo** [comment]
I am having this problem too. 
WP CLI miss a lot of the updates and I need to do more than one run to make sure it works. 
Is there any way to ensure that the system check for updates?

**Comment by rgierke** [comment]
I was running into this as well.  A plugin was updated 2 hours ago, but wordpress doesn't know it's been updated.  This is because wordpress checks every 12 hours to see if there is an update and the time of day that it runs is dependent on when the cron was first started.

`wp plugin list` checks this cached status of if there is an update available, but it does not appear to reach out and check.

To get around this, you can run the cron job to check for updates.

wp cron event run wp_update_plugins

If you're going to work this into your workflow, double check your cron.  This is the only way I've seen it labeled, but check for your own setup.  To check the cron names and the next time it's supposed to run the command is

wp cron event list

If you're attempting to update themes, use
wp cron event run wp_update_themes 

Hopefully this helps until this ever gets incorporated into wp plugin list

**Comment by rgierke** [comment]
I was running into this as well.  A plugin was updated 2 hours ago, but wordpress doesn't know it's been updated.  This is because wordpress checks every 12 hours to see if there is an update and the time of day that it runs is dependent on when the cron was first started.

`wp plugin list` checks this cached status of if there is an update available, but it does not appear to reach out and check.

To get around this, you can run the cron job to check for updates.

`wp cron event run wp_update_plugins`

If you're going to work this into your workflow, double check your cron.  This is the only way I've seen it labeled, but check for your own setup.  To check the cron names and the next time it's supposed to run the command is

`wp cron event list`

If you're attempting to update themes, use
`wp cron event run wp_update_themes`

Hopefully this helps until this ever gets incorporated into wp plugin list
