### ISSUE TITLE
The authenticity of XYZ could not be verified as no signature was found

### ISSUE THREAD

**Issue by catchmyfame** [wp-cli/extension-command#197]
For the past few months I've noticed that when I update plugins via the command line we get 

> The authenticity of XYZ could not be verified as no signature was found

However the update goes along smoothly every time. Why are we seeing this message and is there anything we can do to mitigate it? We're running WordPress 5.2.3.

For example:

```
$ wp plugin update jetpack
Enabling Maintenance mode...
Downloading update from https://downloads.wordpress.org/plugin/jetpack.7.8.zip...
The authenticity of jetpack.7.8.zip could not be verified as no signature was found.
Unpacking the update...
Installing the latest version...
Removing the old version of the plugin...
Plugin updated successfully.
```

**Comment by schlessera** [comment]
This is due to the new infrastructure security enhancements that went into WordPress Core.

WordPress Core now checks signs all downloads and checks against these signatures, so that it notices if it downloads files from an unknown source (man-in-the-middle attack for updates).

However, most of the existing files are not signed yet, so that's why you get this warning.

See https://make.wordpress.org/core/2019/05/17/security-in-5-2/
