### ISSUE TITLE
plugin install —force order of operations

### ISSUE THREAD

**Issue by jimlongo56** [wp-cli/extension-command#20]
When using the `--force` flag on a plugin install the `register_activation_hook()` does not fire because the plugin is already active.

According to the order of output the installation happens before the removal which seems backwards. _See lines 3 and 4 in the output below._

If the order was reversed then shouldn't there be a `register_uninstall_hook()` followed by a `register_activation_hook()`?

```
[~]# wp plugin install myplugin.zip --force --activate
Unpacking the package...
Installing the plugin...
Removing the old version of the plugin...
Plugin updated successfully.
Activating 'myplugin'...
Warning: Plugin 'myplugin' is already active.
Success: Installed 1 of 1 plugins.```

**Comment by schlessera** [comment]
@jimlongo56 there's 2 different issues here.

1.) WP-CLI uses the upgrader to do force installation of an existing plugin. The order of the installation/removal is done by WordPress Core, not by WP-CLI. WP-CLI simply makes use of the upgrader mechanism that Core provides: https://github.com/WordPress/WordPress/blob/064e62cbeac39a062a46a7d2d7e94b297ad5e8c0/wp-admin/includes/class-plugin-upgrader.php

2.) (De-)Activation hooks are not triggered by upgrades by design. Read this post for more info: https://make.wordpress.org/core/2010/10/27/plugin-activation-hooks-no-longer-fire-for-updates/

Maybe we should consider adding a notice to the documentation about how (de)activation hooks are handled?

**Comment by jimlongo56** [comment]
Understood.

Would it be possible to have a hook that fired during a plugin installation (other than activate)?  Seems that it's not currently possible. 

Those discussions you pointed to explain the background, but it seems that the ship has sailed on any discussion around upgrades (circa 2010).

**Comment by danielbachhuber** [comment]
> Would it be possible to have a hook that fired during a plugin installation (other than activate)? Seems that it's not currently possible.

I think this would be more appropriate for WordPress core.

If you're looking for a way of triggering some upgrade or installation procedure, performing the process on `init` is a common pattern other plugins follow.
