### ISSUE TITLE
`wp plugin search` output is polluted by the success message

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/extension-command#53]
The command `wp plugin search debug-bar --field=slug --format=csv` gets polluted by the success message at the top which states `Success: Showing 10 of 429 plugins.`.

This makes it difficult to pipe into another command.

Other commands that implement the `--field` flag don't show this message, for example `wp plugin list --field=name --format=csv`.

**Comment by danielbachhuber** [comment]
This is a bug. `Success:` should only appear when `--format=table` (e.g. non-machine output).

**Comment by BhargavBhandari90** [comment]
@danielbachhuber  @johnbillion  `wp plugin list` command doesn't show the success message in any case.

So why should the `Success:` appear only for `--format=table` ?

**Comment by danielbachhuber** [comment]
> So why should the Success: appear only for `--format=table` ?

In the case of `wp package browse`, the success message shows pagination information (for which we don't have an alternate implementation right now).

`--format=table` is intended for humans, not machines. For machine-readable output (e.g. `--format=json`), we exclude the success message because including it would break the format.
